version: '2.0'
services: 
    web:
        image: nginx:1.13.0-alpine
        container_name: superminiproject
        restart: always
        ports: 
        - "3416:80"
        volumes: 
        - ./project/:/usr/share/nginx/html